services:
  - type: web
    name: cotacoes-backend
    env: python
    plan: free
    branch: deploy-render
    buildCommand: pip install -r requirements.txt && python backend/manage.py migrate && python backend/manage.py collectstatic --noinput
    startCommand: gunicorn cotacoes.wsgi:application --chdir backend
    autoDeploy: true

  - type: static
    name: cotacoes-frontend
    env: static
    plan: free
    branch: deploy-render
    buildCommand: cd frontend && npm install && npm run build
    publishDir: frontend/dist
    autoDeploy: true
    envVars:
      - key: VITE_API_BASE_URL
        value: https://cotacoes-backend.onrender.com/api
